/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-01-11 02:54:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.setup.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.gatein.portal.installer.PortalSetupService;
import org.exoplatform.container.PortalContainer;
import org.exoplatform.services.resources.ResourceBundleService;
import java.util.ResourceBundle;

public final class setup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


  /*
   * JBoss, Home of Professional Open Source.
   * Copyright 2012, Red Hat, Inc., and individual contributors
   * as indicated by the @author tags. See the copyright.txt file in the
   * distribution for a full listing of individual contributors.
   *
   * This is free software; you can redistribute it and/or modify it
   * under the terms of the GNU Lesser General Public License as
   * published by the Free Software Foundation; either version 2.1 of
   * the License, or (at your option) any later version.
   *
   * This software is distributed in the hope that it will be useful,
   * but WITHOUT ANY WARRANTY; without even the implied warranty of
   * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
   * Lesser General Public License for more details.
   *
   * You should have received a copy of the GNU Lesser General Public
   * License along with this software; if not, write to the Free
   * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
   * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
   */

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");


  PortalContainer portalContainer = PortalContainer.getCurrentInstance(session.getServletContext());
  PortalSetupService setupService = (PortalSetupService)portalContainer.getComponentInstance(PortalSetupService.class);
  
  if (setupService.isSetup(request.getContextPath().substring(1))) {
      response.sendRedirect(request.getContextPath());
  }

  String contextPath = request.getContextPath() ;
  String error = (String)request.getAttribute("org.gatein.portal.setup.error");

  ResourceBundleService service = (ResourceBundleService) portalContainer.getComponentInstanceOfType(ResourceBundleService.class);
  ResourceBundle res = service.getResourceBundle(service.getSharedResourceBundleNames(), request.getLocale()) ;

  response.setCharacterEncoding("UTF-8"); 
  response.setContentType("text/html; charset=UTF-8");

      out.write("\n");
      out.write("<!DOCTYPE html\n");
      out.write("PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n");
      out.write("\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("  <head>\n");
      out.write("    <title>");
      out.print(res.getString("UISetupForm.label.setup.SetPasswordTitle"));
      out.write("</title>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>        \n");
      out.write("    <meta name=\"description\" content=\"Password setup screen of the Portal\"/>\n");
      out.write("    <meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\"/>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/portal/setup/css/default.css\"/>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/portal/setup/css/enchanced.css\"/>\n");
      out.write("    <!--[if lte IE 8]>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/portal/setup/css/ie8.css\"/>\n");
      out.write("    <![endif]-->\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <h1><a href=\"#login-form\" title=\"Setup\">");
      out.print(res.getString("UISetupForm.label.setup.SetPasswordTitle"));
      out.write("</a></h1>\n");
      out.write("    ");
/*Begin form*/
      out.write("\n");
      out.write("    ");
 if(error != null) { 
      out.write("\n");
      out.write("    <div id=\"error-pane\"><p><span>");
      out.print( error );
      out.write("</span></p></div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    <form id=\"setup-form\" name=\"setup-form\" action=\"");
      out.print( contextPath + "/setupaction");
      out.write("\" method=\"post\">\n");
      out.write("        <fieldset>\n");
      out.write("            <legend>");
      out.print(res.getString("UISetupForm.label.setup.SetPassword"));
      out.write("</legend>\n");
      out.write("            \n");
      out.write("            <label for=\"password\">");
      out.print(res.getString("UISetupForm.label.setup.Password"));
      out.write("</label>\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\" value=\"\"/>\n");
      out.write("            \n");
      out.write("            <label for=\"password2\">");
      out.print(res.getString("UISetupForm.label.setup.PasswordRep"));
      out.write("</label>\n");
      out.write("            <input type=\"password\" id=\"password2\" name=\"password2\" value=\"\"/>\n");
      out.write("            \n");
      out.write("            <input type=\"submit\" name=\"setup\" value=\"");
      out.print(res.getString("UISetupForm.label.setup.Setup"));
      out.write("\"/>\n");
      out.write("\n");
      out.write("        </fieldset>\n");
      out.write("    </form>\n");
      out.write("    <div id=\"footer\">\n");
      out.write("        <p>\n");
      out.write("            ");
      out.print(res.getString("UISetupForm.label.mobile.copyright.Intro"));
      out.write("\n");
      out.write("            <a href=\"http://www.redhat.com/\">");
      out.print(res.getString("UISetupForm.label.mobile.copyright.RH"));
      out.write("</a>\n");
      out.write("            ");
      out.print(res.getString("UISetupForm.label.mobile.copyright.And"));
      out.write("\n");
      out.write("            <a href=\"http://www.exoplatform.com\">");
      out.print(res.getString("UISetupForm.label.mobile.copyright.Exo"));
      out.write("</a>\n");
      out.write("        </p>\n");
      out.write("    </div>\n");
      out.write("</body>   \n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
